name: Build Static Site with GitHub Repo Data

on:
  push:
    branches:
      - main  # change this to your branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node modules
        run: npm install

      - name: Fetch GitHub repos and save as JSON
        run: node scripts/fetch-github-repos.js
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}